require('harsha.plugins_config.noice')
require('harsha.plugins_config.barbar')
require('harsha.plugins_config.carbon_now')
-- require('harsha.plugins_config.copilot')
require('harsha.plugins_config.gitsigns')
require('harsha.plugins_config.toggleterm')
require('harsha.plugins_config.lazygit')
-- require('harsha.plugins_config.whichkey')
require('harsha.plugins_config.cmp')
require('harsha.plugins_config.symbols-outline')
require('harsha.plugins_config.telescope')
require('harsha.plugins_config.treesitter')
require('harsha.plugins_config.nvim-notify')
-- require('harsha.plugins_config.nvimtree')
require('harsha.plugins_config.persistence')
require('harsha.plugins_config.todo-comments')
require('harsha.plugins_config.zen-mode')
